[build]
  base = "sushi-ui"
  command = "CI=false && npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Content-Security-Policy = "connect-src 'self' https://accounts.google.com https://sushi-api-951508746812.asia-southeast1.run.app https://*.googleapis.com https://www.googleapis.com https://oauth2.googleapis.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 